import { mkdirSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { compileContentGraph } from '../src/content-graph'

const GENERATED_DIR = resolve(import.meta.dirname, '..', 'src', 'content-graph', 'generated')
const OUT_DIR = resolve(import.meta.dirname, '..', 'src')

async function main() {
  console.log('[search-index] Generating search index...')

  const { contentRegistry } = await import('../src/content-registry.generated')

  const graph = compileContentGraph({
    registry: contentRegistry,
    locales: ['en', 'pt', 'es', 'fr', 'de', 'it', 'ja', 'zh'],
    defaultLocale: 'en',
  })

  const publicGroupIds = new Set(graph.groups.publicGroups.flatMap(g => g.nodes.map(n => n.id)))
  const nodes = Array.from(graph.nodes.values())
  const publicNodes = nodes.filter(n => publicGroupIds.has(n.id))

  const documents = publicNodes.map(node => ({
    id: node.id,
    title: node.title,
    summary: node.summary,
    href: node.routes.canonical || `/${node.locale}/signals/${node.niche[0]}/${node.slug}`,
    locale: node.locale,
    tags: node.tags,
  }))

  const searchIndex = {
    version: 'search-index.v1',
    generatedAt: new Date().toISOString(),
    totalDocuments: documents.length,
    documents,
  }

  mkdirSync(GENERATED_DIR, { recursive: true })
  const jsonPath = resolve(GENERATED_DIR, 'search-index.v1.json')
  writeFileSync(jsonPath, JSON.stringify(searchIndex, null, 2), 'utf-8')

  const generatedTs = [
    "import type { SearchIndexDocument } from './content-graph/contracts/search'",
    '// AUTO-GENERATED by scripts/generate-search-index.ts',
    '',
    `const _data: SearchIndexV1_ = JSON.parse(${JSON.stringify(JSON.stringify(searchIndex))})`,
    '',
    'interface SearchIndexV1_ {',
    '  version: string',
    '  generatedAt: string',
    '  totalDocuments: number',
    '  documents: SearchIndexDocument[]',
    '}',
    '',
    'export const searchIndexDocuments: SearchIndexDocument[] = _data.documents',
    'export const searchIndexTotal = _data.totalDocuments',
    '',
  ].join('\n')

  const generatedPath = resolve(OUT_DIR, 'search-index.generated.ts')
  writeFileSync(generatedPath, generatedTs, 'utf-8')

  console.log(`[search-index] Generated ${documents.length} documents`)
  console.log(`[search-index] Written to ${jsonPath}`)
  console.log(`[search-index] Generated barrel at ${generatedPath}`)
}

main().catch(err => {
  console.error('[search-index] Failed:', err)
  process.exit(1)
})
