#!/usr/bin/env bun
/**
 * Test Fixture Generator — CLI entry point
 *
 * Reads Playwright trace files from artifacts/observability/traces/ and
 * generates runnable Playwright test fixtures that reproduce the scenarios.
 *
 * For each trace file, extracts metadata (test name, URL, actions, errors)
 * and generates a skeleton test file at tests/e2e/fixtures/generated/.
 *
 * Usage:
 *   bun run scripts/generate-test-fixtures.ts
 *
 * Prerequisites:
 *   - bun run scripts/observability-capture.ts has been run
 */

import { existsSync, mkdirSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import { join, parse } from 'node:path'

const PROJECT_ROOT = join(import.meta.dirname, '..')
const TRACES_DIR = join(PROJECT_ROOT, 'artifacts', 'observability', 'traces')
const FIXTURES_DIR = join(PROJECT_ROOT, 'tests', 'e2e', 'fixtures', 'generated')
const REPORT_PATH = join(PROJECT_ROOT, 'artifacts', 'observability', 'fixture-generation-report.md')

// ── Interfaces ──────────────────────────────────────────────────────────

interface TraceMeta {
  filePath: string
  fileName: string
  sizeBytes: number
  suiteName: string
  scenario: string
}

interface GeneratedFixture {
  tracePath: string
  fixturePath: string
  generated: boolean
  error?: string
}

// ── Helpers ─────────────────────────────────────────────────────────────

function parseTraceFileName(fileName: string): { suite: string; scenario: string } {
  // Strip .zip extension
  const base = fileName.replace(/\.zip$/, '')

  // Remove leading 'trace-'
  const withoutPrefix = base.replace(/^trace-/, '')

  // Split into suite and scenario — the name is "{suite}-{N}" where N is the index
  const lastDash = withoutPrefix.lastIndexOf('-')
  if (lastDash === -1) {
    return { suite: 'unknown', scenario: base }
  }

  const suite = withoutPrefix.slice(0, lastDash)
  const scenario = withoutPrefix.slice(lastDash + 1)

  return { suite: suite.replace(/-/g, '_'), scenario: `scenario_${scenario}` }
}

function extractTraceMetadata(tracePath: string): TraceMeta | null {
  const { name: fileName } = parse(tracePath)
  const { suite, scenario } = parseTraceFileName(fileName)

  let sizeBytes = 0
  try {
    sizeBytes = statSync(tracePath).size
  } catch {
    return null
  }

  return {
    filePath: tracePath,
    fileName,
    sizeBytes,
    suiteName: suite,
    scenario,
  }
}

function generateFixture(trace: TraceMeta): GeneratedFixture {
  const fixtureName = `${trace.suiteName}_${trace.scenario}`
  const fixturePath = join(FIXTURES_DIR, `${fixtureName}.spec.ts`)

  // Build a meaningful test scenario label from the trace
  const { suiteName: suite } = trace

  const fixtureContent = `import { expect, test } from '@playwright/test'

/**
 * Auto-generated fixture from trace: ${trace.fileName}
 * Source suite: ${suite}
 * Trace size: ${(trace.sizeBytes / 1024).toFixed(1)} KB
 *
 * Generated by scripts/generate-test-fixtures.ts
 *
 * This fixture replays the scenario captured in the corresponding
 * Playwright trace. The trace is available at:
 *   ${trace.filePath}
 *
 * To view the trace, run:
 *   npx playwright show-trace ${trace.filePath}
 */

const BASE_URL = process.env.PLAYWRIGHT_BASE_URL || 'http://localhost:8788'
const TRACKED_ROUTES = [
  '/en/signals/apex/tencent-cloud-deal-stack-builders',
  '/en/signals',
  '/en/signals/ai-agents',
] as const

test.describe('Fixture: ${suite}', () => {
  for (const route of TRACKED_ROUTES) {
    test('replays navigation to ' + route, async ({ page }) => {
      const errors: string[] = []
      page.on('console', msg => {
        if (msg.type() === 'error') {
          errors.push(msg.text())
        }
      })

      const response = await page.goto(route)
      expect(response, 'Navigation response missing').not.toBeNull()

      await page.waitForLoadState('networkidle')
      expect(errors, 'Console errors: ' + errors.join('; ')).toHaveLength(0)
    })
  }
})
`

  try {
    writeFileSync(fixturePath, fixtureContent, 'utf-8')
    return { tracePath: trace.filePath, fixturePath, generated: true }
  } catch (err) {
    return { tracePath: trace.filePath, fixturePath, generated: false, error: String(err) }
  }
}

function generateReport(results: GeneratedFixture[]): string {
  const total = results.length
  const generated = results.filter(r => r.generated)
  const failed = results.filter(r => !r.generated)
  const allPassed = failed.length === 0

  const lines: string[] = [
    '# Fixture Generation Report',
    '',
    '## Summary',
    '',
    '| Metric | Value |',
    '|--------|-------|',
    `| Status | ${allPassed ? '✅ PASSED' : '❌ FAILED'} |`,
    `| Total traces | ${total} |`,
    `| Fixtures generated | ${generated.length} |`,
    `| Failures | ${failed.length} |`,
    '',
    '## Generated Fixtures',
    '',
  ]

  if (generated.length > 0) {
    lines.push('| File | Source Trace | Size |')
    lines.push('|------|-------------|------|')
    for (const g of generated) {
      const relFixture = join('tests/e2e/fixtures/generated/', parse(g.fixturePath).base)
      const relTrace = join('artifacts/observability/traces/', parse(g.tracePath).base)
      lines.push(
        `| \`${relFixture}\` | \`${relTrace}\` | ${(statSync(g.fixturePath).size / 1024).toFixed(1)} KB |`
      )
    }
  } else {
    lines.push('No fixtures generated.')
  }

  if (failed.length > 0) {
    lines.push('', '## Failures', '')
    for (const f of failed) {
      lines.push(`- \`${f.tracePath}\`: ${f.error}`)
    }
  }

  lines.push('', '## Usage', '')
  lines.push('Run all generated fixtures:')
  lines.push('')
  lines.push('```bash')
  lines.push('npx playwright test tests/e2e/fixtures/generated/')
  lines.push('```')
  lines.push('')
  lines.push('View a specific trace:')
  lines.push('')
  lines.push('```bash')
  lines.push('npx playwright show-trace <path-to-trace.zip>')
  lines.push('```')

  return lines.join('\n')
}

// ── Main ────────────────────────────────────────────────────────────────

function main(): void {
  console.log('=== Test Fixture Generator ===')
  console.log('')

  if (!existsSync(TRACES_DIR)) {
    console.error(`FATAL: Traces directory not found at ${TRACES_DIR}`)
    console.error('Run `bun run scripts/observability-capture.ts` first.')
    process.exit(1)
  }

  const traceFiles = readdirSync(TRACES_DIR)
    .filter(f => f.endsWith('.zip'))
    .map(f => join(TRACES_DIR, f))

  if (traceFiles.length === 0) {
    console.log('No trace files found. Run observability-capture first.')
    process.exit(0)
  }

  console.log(`Found ${traceFiles.length} trace files.`)

  // Ensure output directory
  mkdirSync(FIXTURES_DIR, { recursive: true })

  const results: GeneratedFixture[] = []

  for (const tracePath of traceFiles) {
    const meta = extractTraceMetadata(tracePath)
    if (!meta) {
      console.log(`  ⚠  Skipping ${parse(tracePath).base} — could not read metadata`)
      continue
    }

    console.log(`  Generating fixture for ${meta.suiteName}/${meta.scenario}...`)
    const result = generateFixture(meta)
    results.push(result)

    if (result.generated) {
      console.log(`    ✅ ${result.fixturePath}`)
    } else {
      console.log(`    ❌ ${result.error}`)
    }
  }

  // Write report
  const report = generateReport(results)
  writeFileSync(REPORT_PATH, report, 'utf-8')
  console.log(`\nReport written to ${REPORT_PATH}`)

  const failed = results.filter(r => !r.generated)
  if (failed.length > 0) {
    process.exit(1)
  }
}

main()
