import { mkdirSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { compileContentGraph, serializeGraphArtifacts } from '../src/content-graph'

const GENERATED_DIR = resolve(import.meta.dirname, '..', 'src', 'content-graph', 'generated')
const GENERATED_TS = resolve(import.meta.dirname, '..', 'src', 'content-graph.generated.ts')

async function main() {
  console.log('[content-graph] Generating content graph...')

  const { contentRegistry } = await import('../src/content-registry.generated')

  const graph = compileContentGraph({
    registry: contentRegistry,
    locales: ['en', 'pt', 'es', 'fr', 'de', 'it', 'ja', 'zh'],
    defaultLocale: 'en',
  })

  const artifacts = serializeGraphArtifacts(graph)

  mkdirSync(GENERATED_DIR, { recursive: true })

  const files: [string, string][] = [
    ['content-graph.v1.json', JSON.stringify(artifacts.graph, null, 2)],
    ['route-manifest.v1.json', JSON.stringify(artifacts.routeManifest, null, 2)],
    ['locale-index.v1.json', JSON.stringify(artifacts.localeIndex, null, 2)],
    ['taxonomy-index.v1.json', JSON.stringify(artifacts.taxonomyIndex, null, 2)],
    ['related-index.v1.json', JSON.stringify(artifacts.relatedIndex, null, 2)],
    ['visibility-index.v1.json', JSON.stringify(artifacts.visibilityIndex, null, 2)],
  ]

  for (const [filename, data] of files) {
    writeFileSync(resolve(GENERATED_DIR, filename), data, 'utf-8')
  }

  // Also generate a TypeScript module that routes can import
  const graphJson = JSON.stringify(artifacts.graph)
  const escapedJson = graphJson.replace(/\\/g, '\\\\').replace(/'/g, "\\'")
  const generatedTs = [
    '// AUTO-GENERATED by scripts/generate-content-graph.ts',
    "import { createStaticProvider } from './content-graph/loaders/create-static-provider'",
    "import type { SerializableGraphV1 } from './content-graph/contracts/artifacts'",
    '',
    `const _data: SerializableGraphV1 = JSON.parse('${escapedJson}')`,
    '',
    'export const contentGraphProvider = createStaticProvider(_data)',
    'export const contentGraphData = _data',
    '',
  ].join('\n')
  writeFileSync(GENERATED_TS, generatedTs, 'utf-8')

  console.log(`[content-graph] Generated ${graph.metadata.totalNodes} nodes`)
  console.log(`[content-graph] Public: ${graph.collections.public.length}`)
  console.log(`[content-graph] Edges: ${artifacts.graph.edges.length}`)
  console.log(`[content-graph] Written ${files.length} artifact files to ${GENERATED_DIR}`)
  console.log(`[content-graph] Written generated TS module to ${GENERATED_TS}`)
}

main().catch(err => {
  console.error('[content-graph] Failed:', err)
  process.exit(1)
})
