import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { LOCALE_BCP47_TO_V2 } from '@uniteia/content-node-contract'
import { compileContentGraph, serializeGraphArtifacts } from '../src/content-graph'
import type { SerializableGraphV1 } from '../src/content-graph/contracts/artifacts'
import type { ContentLocale } from '../src/content-graph/contracts/node'

const GENERATED_DIR = resolve(import.meta.dirname, '..', 'src', 'content-graph', 'generated')
const GENERATED_TS = resolve(import.meta.dirname, '..', 'src', 'content-graph.generated.ts')
const GENERATED_FULL_TS = resolve(
  import.meta.dirname,
  '..',
  'src',
  'content-graph-full.generated.ts'
)
const CONTENT_METADATA_DIR = resolve(import.meta.dirname, '..', 'content-metadata')

/**
 * Normalize a factory node ID from BCP47 locale prefix to v2 internal locale code.
 */
function normalizeBcp47NodeId(id: string): string {
  for (const [bcp47, v2] of Object.entries(LOCALE_BCP47_TO_V2)) {
    if (bcp47 === v2) continue
    const prefix = `${bcp47}-`
    if (id.startsWith(prefix)) {
      return id.replace(prefix, `${v2}-`)
    }
  }
  return id
}

function normalizeFactoryNode(node: Record<string, unknown>): string {
  const rawId = node.id as string
  const normalizedId = normalizeBcp47NodeId(rawId)

  if (node.locale && LOCALE_BCP47_TO_V2[node.locale as keyof typeof LOCALE_BCP47_TO_V2]) {
    node.locale = LOCALE_BCP47_TO_V2[node.locale as keyof typeof LOCALE_BCP47_TO_V2]
  }
  if (
    node.canonicalLocale &&
    LOCALE_BCP47_TO_V2[node.canonicalLocale as keyof typeof LOCALE_BCP47_TO_V2]
  ) {
    node.canonicalLocale =
      LOCALE_BCP47_TO_V2[node.canonicalLocale as keyof typeof LOCALE_BCP47_TO_V2]
  }

  if (node.alternates && typeof node.alternates === 'object') {
    const normalized: Record<string, string> = {}
    for (const [key, val] of Object.entries(node.alternates)) {
      const v2Key = LOCALE_BCP47_TO_V2[key as keyof typeof LOCALE_BCP47_TO_V2] ?? key
      normalized[v2Key] = typeof val === 'string' ? normalizeBcp47NodeId(val) : String(val)
    }
    node.alternates = normalized
  }

  node.id = normalizedId
  return normalizedId
}

/** Filter content registry to a specific set of locales */
function filterRegistry(
  contentRegistry: Record<string, string>,
  allowedLocales: readonly string[]
): Record<string, string> {
  const filtered: Record<string, string> = {}
  for (const [key, value] of Object.entries(contentRegistry)) {
    const localeMatch = key.match(/\/content\/apex\/([a-z]{2})\//)
    if (localeMatch && (allowedLocales as readonly string[]).includes(localeMatch[1])) {
      filtered[key] = value
    }
  }
  return filtered
}

/** Load factory nodes from content-metadata/ (shared between both compilations) */
function loadFactoryNodes(): Record<string, unknown> {
  const factoryNodes: Record<string, unknown> = {}
  if (existsSync(CONTENT_METADATA_DIR)) {
    const slugs = readdirSync(CONTENT_METADATA_DIR)
    for (const slug of slugs) {
      const nodePath = resolve(CONTENT_METADATA_DIR, slug, 'content-nodes.json')
      if (existsSync(nodePath)) {
        try {
          const nodes = JSON.parse(readFileSync(nodePath, 'utf-8'))
          if (Array.isArray(nodes)) {
            for (const node of nodes) {
              if (node.id) {
                const normalizedId = normalizeFactoryNode(node)
                factoryNodes[normalizedId] = node
              }
            }
          }
        } catch {
          // Skip invalid content-nodes.json
        }
      }
    }
  }
  return factoryNodes
}

/** Write a SerializableGraph as a TypeScript module */
function writeTsModule(filepath: string, graphJson: string, comment: string) {
  const escapedJson = graphJson.replace(/\\/g, '\\\\').replace(/'/g, "\\'")
  const code = [
    '// AUTO-GENERATED by scripts/generate-content-graph.ts',
    `// ${comment}`,
    "import { createStaticProvider } from './content-graph/loaders/create-static-provider'",
    "import type { SerializableGraphV1 } from './content-graph/contracts/artifacts'",
    '',
    `const _data: SerializableGraphV1 = JSON.parse('${escapedJson}')`,
    '',
    'export const contentGraphProvider = createStaticProvider(_data)',
    'export const contentGraphData = _data',
    '',
  ].join('\n')
  writeFileSync(filepath, code, 'utf-8')
}

async function main() {
  const buildLocale = process.env.LOCALE || 'en'
  console.log(`[content-graph] Building — per-locale (${buildLocale}) + full (8 locales)`)

  const { contentRegistry } = await import('../src/content-registry.generated')
  const allLocales = ['en', 'pt', 'es', 'fr', 'de', 'it', 'ja', 'zh'] as const
  const factoryNodes = loadFactoryNodes()
  console.log(
    `[content-graph] Registry: ${Object.keys(contentRegistry).length} entries · ${Object.keys(factoryNodes).length} factory nodes`
  )

  const biomeIgnore = factoryNodes as Record<string, unknown>

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // 1. FULL graph — all 8 locales (for sitemap, MCP API, audit)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  const fullRegistry = filterRegistry(contentRegistry, allLocales)
  const fullGraph = compileContentGraph({
    registry: fullRegistry,
    locales: allLocales as unknown as ContentLocale[],
    defaultLocale: buildLocale as ContentLocale,
    factoryNodes: biomeIgnore as Record<string, unknown>,
  })
  const fullArtifacts = serializeGraphArtifacts(fullGraph)
  fullArtifacts.graph.buildLocale = buildLocale as SerializableGraphV1['buildLocale']

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // 2. PER-LOCALE graph — build locale only (for routes/SSG)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  const perLocaleList = [buildLocale] as readonly string[]
  const perLocaleRegistry = filterRegistry(contentRegistry, perLocaleList)
  const perLocaleGraph = compileContentGraph({
    registry: perLocaleRegistry,
    locales: [buildLocale] as unknown as ContentLocale[],
    defaultLocale: buildLocale as ContentLocale,
    factoryNodes: biomeIgnore as Record<string, unknown>,
  })
  const perLocaleArtifacts = serializeGraphArtifacts(perLocaleGraph)
  perLocaleArtifacts.graph.buildLocale = buildLocale as SerializableGraphV1['buildLocale']

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // WRITE: JSON artifacts (full graph for build tools)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  mkdirSync(GENERATED_DIR, { recursive: true })
  const jsonFiles: [string, string][] = [
    ['content-graph.v1.json', JSON.stringify(fullArtifacts.graph, null, 2)],
    ['route-manifest.v1.json', JSON.stringify(fullArtifacts.routeManifest, null, 2)],
    ['locale-index.v1.json', JSON.stringify(fullArtifacts.localeIndex, null, 2)],
    ['taxonomy-index.v1.json', JSON.stringify(fullArtifacts.taxonomyIndex, null, 2)],
    ['related-index.v1.json', JSON.stringify(fullArtifacts.relatedIndex, null, 2)],
    ['visibility-index.v1.json', JSON.stringify(fullArtifacts.visibilityIndex, null, 2)],
  ]
  for (const [filename, data] of jsonFiles) {
    writeFileSync(resolve(GENERATED_DIR, filename), data, 'utf-8')
  }

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // WRITE: TypeScript modules
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  const perLocaleJson = JSON.stringify(perLocaleArtifacts.graph)
  const fullJson = JSON.stringify(fullArtifacts.graph)

  writeTsModule(GENERATED_TS, perLocaleJson, `PER-LOCALE (${buildLocale}) — routes/SSG import this`)
  writeTsModule(GENERATED_FULL_TS, fullJson, 'FULL (8 locales) — sitemap, MCP API, audit scripts')

  console.log(
    `[content-graph] Full:     ${fullArtifacts.graph.nodes.length} nodes · ${fullArtifacts.graph.edges.length} edges · ~${Math.round(fullJson.length / 1024)}KB`
  )
  console.log(
    `[content-graph] Per-loc:  ${perLocaleArtifacts.graph.nodes.length} nodes · ${perLocaleArtifacts.graph.edges.length} edges · ~${Math.round(perLocaleJson.length / 1024)}KB`
  )
  console.log(
    `[content-graph] Savings:  ${Math.round((1 - perLocaleJson.length / fullJson.length) * 100)}% smaller`
  )
  console.log(`[content-graph] Written:  ${GENERATED_TS}, ${GENERATED_FULL_TS}`)
}

main().catch(err => {
  console.error('[content-graph] Failed:', err)
  process.exit(1)
})
