/**
 * Evidence Collection Types
 *
 * Type definitions for Stage 1 (Research) evidence collection.
 * These types support web source fetching, content extraction,
 * and research brief generation.
 */

/**
 * Source classification types
 */
export type SourceKind =
  | "primary"
  | "official"
  | "news"
  | "blog"
  | "review"
  | "social"
  | "academic"
  | "documentation";

/**
 * Source metadata from research phase
 *
 * Represents a single web source that was collected during research.
 * Tracks URL, kind, access timestamp, and extraction status.
 */
export interface Source {
  /** Source URL (must be valid URI) */
  url: string;

  /** Source type classification */
  kind: SourceKind;

  /** ISO 8601 date when source was accessed */
  accessed_at: string;

  /** Reference to excerpt in artifacts/extracts.json (e.g., ex_001) */
  excerpt_id?: string;

  /** Source title (optional) */
  title?: string;
}

/**
 * Extraction status for a source
 */
export type ExtractionStatus =
  | "pending"
  | "success"
  | "failed"
  | "skipped";

/**
 * Extracted evidence from a single source
 *
 * Represents structured evidence extracted from a web page.
 * Includes relevance scoring and extraction metadata.
 */
export interface Extract {
  /** ID of the source this extract came from */
  source_id: string;

  /** Extracted title (from page metadata) */
  title?: string;

  /** Extracted content (main text content) */
  content: string;

  /** Relevance score (0-1, where 1 is most relevant) */
  relevance_score: number;

  /** Extraction status */
  status: ExtractionStatus;

  /** Error message if extraction failed */
  error?: string;

  /** ISO 8601 timestamp when extraction was performed */
  extracted_at: string;

  /** Key facts extracted from the source */
  key_facts?: string[];

  /** Metadata from the source (author, date, etc.) */
  metadata?: Record<string, unknown>;
}

/**
 * Research brief artifact
 *
 * Generated by Stage 1 (Research) after collecting and extracting
 * evidence from multiple sources. Used as input for Stage 2 (Draft).
 */
export interface ResearchBrief {
  /** Entity being researched */
  entity: string;

  /** ISO 8601 timestamp when brief was generated */
  generated_at: string;

  /** Total number of sources collected */
  source_count: number;

  /** Number of successful extractions */
  successful_extractions: number;

  /** Overall confidence score (0-1) */
  confidence_score: number;

  /** All collected sources */
  sources: Source[];

  /** All extracted evidence */
  extracts: Extract[];

  /** Synthesis summary */
  synthesis?: string;

  /** Key findings across all sources */
  key_findings: string[];

  /** Research gaps identified */
  gaps?: string[];

  /** Suggested next steps */
  next_steps?: string[];
}

/**
 * Type guard for SourceKind
 */
export function isSourceKind(value: unknown): value is SourceKind {
  const validKinds: SourceKind[] = [
    "primary",
    "official",
    "news",
    "blog",
    "review",
    "social",
    "academic",
    "documentation",
  ];
  return typeof value === "string" && validKinds.includes(value as SourceKind);
}

/**
 * Type guard for Source
 */
export function isSource(value: unknown): value is Source {
  if (typeof value !== "object" || value === null) return false;

  const obj = value as Record<string, unknown>;

  return (
    typeof obj.url === "string" &&
    isSourceKind(obj.kind) &&
    typeof obj.accessed_at === "string"
  );
}

/**
 * Type guard for ExtractionStatus
 */
export function isExtractionStatus(value: unknown): value is ExtractionStatus {
  const validStatuses: ExtractionStatus[] = [
    "pending",
    "success",
    "failed",
    "skipped",
  ];
  return typeof value === "string" && validStatuses.includes(value as ExtractionStatus);
}

/**
 * Type guard for Extract
 */
export function isExtract(value: unknown): value is Extract {
  if (typeof value !== "object" || value === null) return false;

  const obj = value as Record<string, unknown>;

  return (
    typeof obj.source_id === "string" &&
    typeof obj.content === "string" &&
    typeof obj.relevance_score === "number" &&
    isExtractionStatus(obj.status) &&
    typeof obj.extracted_at === "string"
  );
}

/**
 * Type guard for ResearchBrief
 */
export function isResearchBrief(value: unknown): value is ResearchBrief {
  if (typeof value !== "object" || value === null) return false;

  const obj = value as Record<string, unknown>;

  return (
    typeof obj.entity === "string" &&
    typeof obj.generated_at === "string" &&
    typeof obj.source_count === "number" &&
    typeof obj.successful_extractions === "number" &&
    typeof obj.confidence_score === "number" &&
    Array.isArray(obj.sources) &&
    Array.isArray(obj.extracts) &&
    Array.isArray(obj.key_findings)
  );
}
