import type { SearchIndexDocument } from './content-graph/contracts/search'
// AUTO-GENERATED by scripts/generate-search-index.ts

const _data: SearchIndexV1_ = JSON.parse("{\"version\":\"search-index.v1\",\"generatedAt\":\"2026-05-16T17:31:55.313Z\",\"totalDocuments\":1,\"documents\":[{\"id\":\"en-llm-aggregators-compared\",\"title\":\"LLM Aggregators Compared\",\"summary\":\"A comprehensive look at current LLM aggregators and how they facilitate multi-model workflows.\\n\\n Overview\\n\\nIn the rapidly evolving AI landscape, aggregators provide a single point of access to\",\"href\":\"/en/n/ai-agents/llm-aggregators-compared\",\"locale\":\"en\",\"tags\":[\"llm\",\"aggregators\",\"ai-agents\"]}]}")

interface SearchIndexV1_ {
  version: string
  generatedAt: string
  totalDocuments: number
  documents: SearchIndexDocument[]
}

export const searchIndexDocuments: SearchIndexDocument[] = _data.documents
export const searchIndexTotal = _data.totalDocuments
